language: node_js
node_js:
    - 14

cache: yarn


script: gridsome build

before_install: cd blog

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: ./blog/dist
    target_branch: build
    on:
      branch: master