# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        default: 'warning'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      

      - name: Cache multiple paths
        uses: actions/cache@v2
        id: node-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-nodes-${{ hashFiles('./blog/yarn.lock') }}
      
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        
      - name: install Yarn
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: |
            cd blog
            yarn --frozen-lockfile
            cd ..
      
      - name: Build Gridsome files
        run: |
            cd blog
            npm run build
            cd ..

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog/dist
          publish_branch: build
